FROM php:7.2-fpm-alpine

# alpine-sdk and autoconf to be able to install iconv & xdebug
# icu-dev to be able to install intl
# zip to allow Composer to download dependencies from dist

ENV TERM xterm

RUN apk add --update alpine-sdk rsync bash autoconf curl freetype-dev gdb git htop icu-dev libmcrypt-dev libtool libltdl \
        libjpeg-turbo-dev make re2c strace tzdata zip pcre-dev libxml2-dev libldap openldap-dev openssh nodejs \
    # install shadow (usermod, useradd, ...)
    && apk add --update shadow --update-cache --repository https://dl-cdn.alpinelinux.org/alpine/v3.7/community \
    # install postgresql 10.3
    && apk add --update postgresql=10.3-r0 postgresql-dev=10.3-r0 --update-cache --repository https://dl-cdn.alpinelinux.org/alpine/v3.7/main \
    # composer
    && curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    # deployer
    && curl -LO https://deployer.org/deployer.phar \
    && mv deployer.phar /usr/local/bin/dep \
    && chmod +x /usr/local/bin/dep \
    # install php extensions
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(getconf _NPROCESSORS_ONLN) gd intl pdo_pgsql zip bcmath exif soap ldap \
    # enable opcache
    && docker-php-ext-enable opcache \
    # set timezone
    && cp /usr/share/zoneinfo/Asia/Ho_Chi_Minh /etc/localtime \
    && echo "Asia/Ho_Chi_Minh" > /etc/timezone \
    # iconv issue https://github.com/docker-library/php/issues/240
    && rm /usr/bin/iconv \
    && curl -SL http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.15.tar.gz | tar -xz -C . \
    && cd libiconv-1.15 \
    && ./configure --prefix=/usr/local \
    && make \
    && make install \
    && libtool --finish /usr/local/lib \
    && cd .. \
    && rm -rf libiconv-1.15 \
    # xdebug install for local env (disabled by default)
    && set -xe \
    && curl -sSL https://github.com/xdebug/xdebug/archive/2.6.0.tar.gz | tar xz -C /tmp \
    && cd /tmp/xdebug-2.6.0 && phpize && ./configure --enable-xdebug && make && make install \
    # php timecop extension (for testing)
    && curl -sSL https://github.com/hnw/php-timecop/archive/master.tar.gz | tar xz -C /tmp \
    && cd /tmp/php-timecop-master && phpize && ./configure --enable-timecop && make && make install \
    && apk del --purge alpine-sdk autoconf libtool re2c tzdata \
    && rm -rf /usr/src/php.tar* /var/cache/apk/* /tmp/xdebug* /tmp/php-timecop*

ENV LD_PRELOAD /usr/local/lib/preloadable_libiconv.so

USER www-data