version: "3"
services:
    selenium-hub:
        image: selenium/hub
        ports:
            - "4444:4444"
        environment:
            GRID_TIMEOUT: 0
        external_links:
            - ${COMPOSE_PROJECT_NAME}_nginx_1

    chrome:
        image: selenium/node-chrome
        links:
            - selenium-hub:hub
        volumes:
            - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
        depends_on:
            - selenium-hub
        external_links:
            - ${COMPOSE_PROJECT_NAME}_nginx_1
        environment:
            HUB_PORT_4444_TCP_ADDR: hub
            HUB_PORT_4444_TCP_PORT: 4444
            NODE_MAX_SESSION: 10
            NODE_MAX_INSTANCES: 10
            SCREEN_WIDTH: 1920
            SCREEN_HEIGHT: 1080
            NODE_APPLICATION_NAME: ${COMPOSE_PROJECT_NAME}

    firefox:
        image: selenium/node-firefox
        links:
            - selenium-hub:hub
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - selenium-hub
        external_links:
            - ${COMPOSE_PROJECT_NAME}_nginx_1
        environment:
            HUB_PORT_4444_TCP_ADDR: hub
            HUB_PORT_4444_TCP_PORT: 4444
            NODE_MAX_SESSION: 10
            NODE_MAX_INSTANCES: 10
            SCREEN_WIDTH: 1920
            SCREEN_HEIGHT: 1080
            NODE_APPLICATION_NAME: ${COMPOSE_PROJECT_NAME}

    chrome_debug:
        image: selenium/node-chrome-debug
        ports:
            - "5900"
        links:
            - selenium-hub:hub
        volumes:
            - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
        depends_on:
            - selenium-hub
        external_links:
            - ${COMPOSE_PROJECT_NAME}_nginx_1
        environment:
            HUB_PORT_4444_TCP_ADDR: hub
            HUB_PORT_4444_TCP_PORT: 4444
            NODE_MAX_SESSION: 10
            NODE_MAX_INSTANCES: 10
            SCREEN_WIDTH: 1920
            SCREEN_HEIGHT: 1080
            NODE_APPLICATION_NAME: ${COMPOSE_PROJECT_NAME}_debug

    firefox_debug:
        image: selenium/node-firefox-debug
        ports:
            - "5900"
        links:
            - selenium-hub:hub
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - selenium-hub
        external_links:
            - ${COMPOSE_PROJECT_NAME}_nginx_1
        environment:
            HUB_PORT_4444_TCP_ADDR: hub
            HUB_PORT_4444_TCP_PORT: 4444
            NODE_MAX_SESSION: 10
            NODE_MAX_INSTANCES: 10
            SCREEN_WIDTH: 1920
            SCREEN_HEIGHT: 1080
            NODE_APPLICATION_NAME: ${COMPOSE_PROJECT_NAME}_debug

networks:
    default:
        external:
            name: ${COMPOSE_PROJECT_NAME}_default